name: Deployment Monitor

on:
  workflow_run:
    workflows: ["Deploy Application"]
    types:
      - completed

jobs:
  notify-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get error logs
        id: get_logs
        run: |
          RUN_ID=${{ github.event.workflow_run.id }}
          
          # Retrieve the logs of the job that failed
          LOGS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                     -H "Accept: application/vnd.github.v3+json" \
                     "https://api.github.com/repos/${{ github.repository }}/actions/runs/${RUN_ID}/jobs")
          
          # Debug: Check the response from the GitHub API
          echo "Job logs response: $LOGS"
          
          # Extracting the job ID for the failed job "deploy"
          JOB_ID=$(echo "$LOGS" | jq -r '.jobs[] | select(.name == "deploy") | .id')
          
          # Debug: Check if JOB_ID was correctly extracted
          echo "Extracted JOB ID: $JOB_ID"
          
          if [ -z "$JOB_ID" ]; then
            echo "No job found with the name 'deploy'."
            exit 1
          fi
          
          # Fetch the logs for the job ID
          JOB_LOGS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          "https://api.github.com/repos/${{ github.repository }}/actions/jobs/$JOB_ID/logs")
          
          # Debug: Check if logs were fetched
          echo "Job logs: $JOB_LOGS"
          
          # Store the logs
          echo "$JOB_LOGS" > deployment_logs.txt

      - name: Debug log file content
        run: cat deployment_logs.txt  # This will print the logs to the Actions console

      - name: Send notification
        run: |
          ERROR_LOGS=$(cat deployment_logs.txt | jq -sR .)
          RESPONSE=$(curl -X POST https://cbc2-210-212-183-2.ngrok-free.app \
            -H "Content-Type: application/json" \
            -d "{
              \"repository\": \"${{ github.repository }}\",
              \"workflow\": \"${{ github.event.workflow_run.name }}\",
              \"status\": \"failed\",
              \"error_logs\": ${ERROR_LOGS},
              \"commit_sha\": \"${{ github.event.workflow_run.head_sha }}\",
              \"commit_message\": \"${{ github.event.workflow_run.head_commit.message }}\"
            }")
          echo "Response: $RESPONSE"
