name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run API error tests
        run: |
          python api_errors.py > output.log 2>&1
        timeout-minutes: 2

      - name: Print error logs
        if: failure()
        run: |
          echo "API error test failed. Logs:"
          cat output.log
